import type { Metadata } from 'next';
import { getTranslations } from 'next-intl/server';
import { site, type Practice } from './site';

const KEYWORDS: Record<string, string[]> = {
  en: [
    'Dr Pakataridis',
    'Paraskevas Pakataridis',
    'personal physician Greece',
    'private doctor Greece',
    'second opinion',
    'research mentoring',
    'how to publish medical research',
    'medical simulation',
  ],
  el: [
    'Πακαταρίδης',
    'Παρασκευάς Πακαταρίδης',
    'προσωπικός ιατρός',
    'ιδιώτης ιατρός',
    'δεύτερη γνώμη',
    'ιατρική έρευνα',
    'δημοσιεύσεις',
    'ιατρική προσομοίωση',
  ],
};

/* Title, description, canonical/alternate URLs and social cards for a page.
   The share image is generated by app/[locale]/opengraph-image.tsx; it is
   referenced explicitly because a page's own openGraph object would otherwise
   drop the inherited image. */
export async function pageMetadata(
  locale: string,
  page: 'home' | 'privacy' | Practice,
): Promise<Metadata> {
  const t = await getTranslations({ locale, namespace: 'Meta' });
  const path = page === 'home' ? '' : `/${page}`;
  const urlFor = (l: string) => `${site.url}${l === 'en' ? '' : `/${l}`}${path}`;
  const title = t(`${page}.title`);
  const description = t(`${page}.description`);
  const ogLocale = locale === 'el' ? 'el_GR' : 'en_GB';
  const image = { url: `/${locale}/opengraph-image`, width: 1200, height: 630, alt: title };

  return {
    title,
    description,
    keywords: KEYWORDS[locale] ?? KEYWORDS.en,
    alternates: {
      canonical: urlFor(locale),
      languages: { en: urlFor('en'), el: urlFor('el') },
    },
    openGraph: {
      type: 'website',
      url: urlFor(locale),
      siteName: 'Dr. Pakataridis',
      title,
      description,
      locale: ogLocale,
      alternateLocale: ogLocale === 'el_GR' ? ['en_GB'] : ['el_GR'],
      images: [image],
    },
    twitter: { card: 'summary_large_image', title, description, images: [image.url] },
  };
}
